title: Decentralized AI

# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Your name to show in the footer
author: Keith Ammon

social-network-links:
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
 # facebook: deanattali
 # github: daattali
 # twitter: daattali
 # patreon: DeanAttali
 # youtube: "@daattali"
 # whatsapp: 15551212
 linktree: https://linktr.ee/keith.ammon
