title: Decentralized AI

# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme
